name = "lingo-bot"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[rules]]
type = "Text"
globs = ["**/*.txt"]
fallthrough = true

[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = "f52064a47e45407faa18265991a88f8b"
